name: PUSH_B) Components Build

on:
  push:
    paths:
      - components/artifacts/**
      - components/recipes/**
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  # region
  AWS_DEFAULT_REGION: ap-northeast-1
  # s3 bucket
  BUCKET_ARTIFACTS: iotlab-artifacts-d325aa
  # base directory
  WORKING_DIRECTORY: components

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Detect changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            components/**

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Save to storage
      - name: Storage
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            bucket_key=${file:21}
            local_path=${file:11}
            aws s3 cp $path s3://$BUCKET_ARTIFACTS/components/$bucket_key
          done
