name: PUSH_B) Lambda Build

on:
  push:
    paths:
      - backend/kinesis_stream_events/**
      - .github/workflows/push_lambda.yml
    branches-ignore:
      - releases/**
  workflow_dispatch:

env:
  # region
  AWS_DEFAULT_REGION: ap-northeast-1
  # base directory
  WORKING_DIRECTORY: backend
  # materials bucket
  BUCKET_MATERIALS: iotlab-materials-654ba1

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Install and Build
      - name: Build
        run: |
          yarn install
          yarn build

      # Save to storage
      - name: Storage
        run: |
          sh configs/package.sh
          aws s3 sync ./zipped/ s3://$BUCKET_MATERIALS/lambda/ --no-progress --only-show-errors
