name: PUSH_T) Terraform Build

on:
  push:
    paths:
      - terraform/**
      - .github/workflows/push_terraform.yml
      - .github/workflows/reuse_terraform.yml
    branches-ignore:
      - releases/**

jobs:
  Infrastructure:
    uses: ./.github/workflows/reuse_terraform.yml
    with:
      region: ap-northeast-1
      working-directory: terraform
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
